name: Prepare build environment
runs:
  using: composite
  steps:
    - name: Copy GitHub specific scripts to git-root folder
      run: cp -va ./.github/scripts/ ./ ; date +%s > ./epoch_job_start.txt
      shell: bash
    - name: Prepare Xcode
      run: ./github_prepare_xcode.sh
      shell: bash
    - name: Cleanup Android Related Stuff
      run: sudo rm -rf $ANDROID_HOME
      shell: bash
    - name: Disable Spotlight
      run: sudo mdutil -a -i off
      shell: bash
    - name: Setup Environment and Toolchain
      run: ./github_setup_env_toolchain.sh ${{ inputs.arch }} | tee -a github_actions_setup_env_toolchain.log
      shell: bash
